import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/layouts';

const Home: NextPage = () => (
  <Layout>
    <Head>
      <title>Multi Send</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  </Layout>
);

export default Home;
